### ISSUE TITLE
Parsing a MSSQL JDBC URL fails

### ISSUE THREAD

**Issue by dmikusa** [pivotal-cf/java-cfenv#189]
The MSSQL JDBC URL: `sqlserver://username:passwordg@host:1433/database` fails to parse on cf-javaenv-boot 2.4.0.

It throws an exception:

```
java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 195
  2022-06-30T14:26:27.57+1000 [APP/PROC/WEB/0] OUT at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
  2022-06-30T14:26:27.57+1000 [APP/PROC/WEB/0] OUT at java.base/java.lang.String.substring(Unknown Source)
  2022-06-30T14:26:27.57+1000 [APP/PROC/WEB/0] OUT at io.pivotal.cfenv.jdbc.SqlServerJdbcUrlCreator.buildJdbcUrlFromUriField(SqlServerJdbcUrlCreator.java:45)
  2022-06-30T14:26:27.57+1000 [APP/PROC/WEB/0] OUT at io.pivotal.cfenv.jdbc.AbstractJdbcUrlCreator.createJdbcUrl(AbstractJdbcUrlCreator.java:49)
  2022-06-30T14:26:27.57+1000 [APP/PROC/WEB/0] OUT at io.pivotal.cfenv.jdbc.CfJdbcUrlCreator.<init>(CfJdbcUrlCreator.java:45)
  2022-06-30T14:26:27.57+1000 [APP/PROC/WEB/0] OUT at io.pivotal.cfenv.jdbc.CfJdbcEnv.findJdbcServices(CfJdbcEnv.java:34)
  2022-06-30T14:26:27.57+1000 [APP/PROC/WEB/0] OUT at io.pivotal.cfenv.spring.boot.CfDataSourceEnvironmentPostProcessor.postProcessEnvironment(CfDataSourceEnvironmentPostProcessor.java:73)
...
```

**Comment by pivotal-david-osullivan** [comment]
Resolved in v2.4.1
