### ISSUE TITLE
NPE when credentials are null in VCAP_SERVICES

### ISSUE THREAD

**Issue by chahlhind** [pivotal-cf/java-cfenv#44]
Hello,

we have some services in our CloudFoundry environment that have no credentials. These services are bound with `credentials: null` in VCAP_SERVICES, e.g.
```
"aws_efs": [
   {
    "binding_name": null,
    "credentials": null,
    "instance_name": "efs_storage",
    "label": "aws_efs",
    "name": "efs_storage",
    "plan": "gp_io",
    "provider": null,
    "syslog_drain_url": null,
    "tags": [
     "efs",
     "nfs",
     "filesystem"
    ],
    "volume_mounts": [
     {
      "container_dir": "/var/vcap/data/0c729062-6ea7-4842-a965-b7a6f8h4t218",
      "device_type": "shared",
      "mode": "rw"
     }
    ]
   }
  ]
```

This causes a NullPointerException:
```
2019-03-14T09:23:20.80+0100 [APP/PROC/WEB/0] OUT 08:23:20.808 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
   2019-03-14T09:23:20.80+0100 [APP/PROC/WEB/0] OUT java.lang.NullPointerException: null
   2019-03-14T09:23:20.80+0100 [APP/PROC/WEB/0] OUT 	at io.pivotal.cfenv.core.CfService.existsByCredentialsContainsUriField(CfService.java:142)
   2019-03-14T09:23:20.80+0100 [APP/PROC/WEB/0] OUT 	at io.pivotal.cfenv.spring.boot.RedisCfEnvProcessor.accept(RedisCfEnvProcessor.java:40)
   2019-03-14T09:23:20.80+0100 [APP/PROC/WEB/0] OUT 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
   2019-03-14T09:23:20.80+0100 [APP/PROC/WEB/0] OUT 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
   2019-03-14T09:23:20.80+0100 [APP/PROC/WEB/0] OUT 	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
   2019-03-14T09:23:20.80+0100 [APP/PROC/WEB/0] OUT 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
   2019-03-14T09:23:20.80+0100 [APP/PROC/WEB/0] OUT 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
   2019-03-14T09:23:20.80+0100 [APP/PROC/WEB/0] OUT 	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
   2019-03-14T09:23:20.80+0100 [APP/PROC/WEB/0] OUT 	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
   2019-03-14T09:23:20.80+0100 [APP/PROC/WEB/0] OUT 	at io.pivotal.cfenv.spring.boot.CfEnvironmentPostProcessor.postProcessEnvironment(CfEnvironmentPostProcessor.java:93)
...
```

I think the cause is `io.pivotal.cfenv.core.CfService#createCredentials()` that checks if the credentials key is present instead of testing if the value is not null.

**Comment by markpollack** [comment]
Thanks!  Fixed in b756a0f181be298d89e598402b0dc928a1926fcb

**Comment by DennisDenuto** [comment]
Out of curiosity @chahlhind  Which service broker did you use to generate the 'aws_efs' service in your example?

**Comment by chahlhind** [comment]
Unfortunately I don't now what service broker is exactly used, because I do not administrate the environment. 
My guess would be it is this one: https://github.com/cloudfoundry-incubator/efs-volume-release

**Comment by DennisDenuto** [comment]
@chahlhind no worries! thanks for replying.

**Comment by mpolhind** [comment]
can you say weather this issue will be included in the next release and when it will be released? We are waiting for this fixed issue.
